[package]
name = "advent-of-code-2023"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[[bin]]
name = "day01a"
path = "bin/day01a.rs"

[[bin]]
name = "day01b"
path = "bin/day01b.rs"


[dependencies]
